spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: order-microservice
          uri: lb://order-microservice
          predicates:
            - Path=/api/orders/**
        - id: shipment-microservice
          uri: lb://shipment-microservice
          predicates:
            - Path=/api/shipments/**
        - id: payment-microservice
          uri: lb://payment-microservice
          predicates:
            - Path=/api/payments/**

server:
  port: 8181

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/